[project]
name = "projectforbank"
version = "0.1.0"
description = "Simple banking system using FastAPI"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.116.1",
]
